spring.application.name=agrofacil
spring.datasource.url=jdbc:mysql://localhost:3306/agrofacil?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false